RequestHeader header

CtrlMode mode

# ---------------------------------------------------- req
---
# ---------------------------------------------------  resp

ResponseHeader header

RetCode ret
